language: ruby
rvm:
- 2.4.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
- sudo apt-get -y install rsync
- chmod +x ./script/cibuild
script: "./script/cibuild"
before_deploy:
- openssl aes-256-cbc -K $encrypted_b8a0c431e644_key -iv $encrypted_b8a0c431e644_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy\_rsa
- ssh-add ./deploy\_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\nPasswordAuthentication no\n" >> ~/.ssh/config
cache: bundler
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after /home/travis/build/tawilkinson/tawilkinson/_site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
