language: ruby
rvm:
- 2.4.1
before_install:
- openssl aes-256-cbc -K $encrypted_b8a0c431e644_key -iv $encrypted_b8a0c431e644_iv
  -in deploy_rsa.enc -out deploy_rsa -d
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
after_success:
- chmod +x script/deploy.sh
- script/deploy.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts:
  - tawilkinson.duckdns.org
  apt:
    packages:
    - libcurl4-openssl-dev
    - sshpass
sudo: false
cache: bundler
