language: ruby
rvm:
- 2.4.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: qYQWZWh98uhmvLeiIPjkL8QSH8lHOo3PFTkc8pnD3n/vpT3WRFLe4G3YRCTQYqd7z3jaXONqVtv0pdZgRloxHbQnoBin+yzeAn89hltp6tK+TLn382RIo/mKyzdW3xvJOXq/LyikP6B0vdizitXXfAgJEA/qefttyrs+6+cxsgkmMZlWISPAAKWFu1j6jK/zAQ2WYAuTJehK+2PUKp72eamQkk2/sti1l7KqLYNhiJDV97MvBHBBjGFU639GckKxhOgtfv3iBH0xuefLrZ5LT+eXPpJak4EZENWurmNx2cX9ZmQmE1aaBTsBvU644CGrpv5PcgyxbZINxLWjwEYnKI20TGjPOKxfda2vSPbJIWv6qKPXODZo374SU5W7vmlq2tj7Eg7SUKg1xEO/CoQXfTc3R9md/7C2Zyl9UI52ZEDwF8/xkyrzh6FRFaotZhtruoIi0bzDpAFB6NxlhAMTVpYMOL9g33+ZJKq40JoIhTdtXgt5TzHny9wGxUGDx6cU1NnHGTjF8pBTNsYAJHjp+GJEbQiri1L/2P7esYCTwt7G7X6sRgnKTTFgHmyJU1jiefjbsEUBTFvxNtKI+07ZHAFJUaUcptHp0a6+l8zbUfE6l7VsMkg+QhZdzgSPj/wmLbDaXlnjkYynC5EhcX7sWumGUzW0L1WGUW668U4AFxw=
  - secure: HU8toKeKI43CIL8d/zWI+XAQbcpGMWMLgL/jq/V2Rr37PLkSvyKr9WD/nWUHLyaqp5OiuqsV+Sj4h44IQdzAz3WVAHBEGbZTU17E4KSqB6jHr4juVPmcnda/a9tPsyZ8ZLl8Dmg08Q54bQZbrxyVViyli23RNJg2IBdqhTiXTWUeONxm8T385SHl23Qi1ZNhh9n6jPxrX4o68+SIlIlYb4+uvmLRhd5b7raG3gXAFB4cBiN6On2IO78Wbm8G1658idiO2CWYnlZ3YBdn4tWx4YWIEqQBb2M2srYO0LUQ/1yKmyiDmc0FAvk2tb/7qSks9cS+i78KkcD/9IYpMqcMdyylxncRVz0bTg/C/MHswClXqMj2u/D+9V48EtCEOF8y4ZZaZ8pkwA1gbTH3eGSVoe8scjBopAePK/PgRroLdou3OflYWnU2eCd9epCO2+GqdKuMwgA/hQmm/LYk/UgJVYOxWu2H96XDwSABtJeWLvtJ2MMYWGd8drK1A+QvTa4ATZVbO0wuEntyjQRJyX3K1ks0WSRVZ0Z4YK1yYyUZ+OBGcq5O4QM6BXDd8+2sMVtqLUJBbBCSUCvtYFzhbsxUWxQ+17INDbywyeDveLu/PIl04qi022NNc9YybGJIjmdtzg/fB/O/bLfzqfKa+JoegzAzFKBK9PalqGXMsVRetTY=
  - secure: n9JFRrbhaFObxh6wTe2o3vMODr7iwkJnnCcaugsovKlwlCFPvkEOvBj0VOzXb299QoxCbAveMnWWiOqid0xXq50/k4GG6mgwtiQaqm29B0o5nN3aKZbE/QMJMX4b8yvTF0TeL+dVSsdkXivNCU7Trwer6mx0NbDQs705rbGBuhQPmQ0yu226xqLePDQzKQYI2d5q00uTdQRWudf28JOdvHrryDvP4yEQDVlV0ovktDh4yT0VuosLcAIvqCnBzrKOC+cwcbzZuAKEYaGiZlyWGnOTiezbqMeBq82mBPhh7AXe3Xg0sNKTbAR5lKx+thlhujS31p//FCEbBDbHEfyKVOLqN/Fdy28jlWmQKFuHFQ2wbDfo2rMGB/Mnt4Okkpy5K7rWYwTsMR6zXv0HpT/eKJBLCzC3Z4lM6VoUS5r28a10W6911SNNVm4JHKlrTbuNoPviMerlJcSX0UC9j+u6eoTKYIJyMULXojvAJMuvhNcqJy0rIYBQ1xtO2Z0/FhUqnQKIYtzhT9w4vfXMthU0VLhKFRhdui4vO26DgqU5trjcGPTefF7IT8/b1xJrnHVBR0D5a4vytQeisz+GwABPvOkqnFawXHov8XHRWYPyhn2hxzLxw6eoXLwRDUCOm7lHEX4Bl43+72sIcXlvpIt0ab3R9KcmQ8XeTvYCqmASX60=
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
# after_success:
# - chmod +x script/deploy.sh
# - script/deploy.sh
before_deploy:
- openssl aes-256-cbc -K $encrypted_b8a0c431e644_key -iv $encrypted_b8a0c431e644_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy\_rsa
- ssh-add ./deploy\_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
# addons:
#  ssh_known_hosts:
#  - tawilkinson.duckdns.org
#  apt:
#    packages:
#    - libcurl4-openssl-dev
#    - sshpass
sudo: false
cache: bundler
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
