title: Tinker Tailor Soldier Sponge
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title
exclude: [vendor]
excerpt_separator: <!--more-->
plugins:
- "jekyll-sitemap"
- "jekyll-redirect-from"
- "jekyll-feed"
- "jekyll-seo-tag"
feed:
  categories:
    - cv
    - author
    - RPG
