name: Jekyll site CI

on:
  push:
    branches:
      - master

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build site
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -p 4000:4000 -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:4.2.0 /bin/bash -c "chmod +x script/ci-build.sh && ./script/ci-build.sh"
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build
      - name: Deploy via rsync
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
          RSYNC_TARGET: ${{ secrets.WEBPATH }}/tar
          RSYNC_SOURCE: build/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SSH_USERNAME: ${{ secrets.USERNAME }}
          SSH_HOSTNAME: ${{ secrets.HOST }}
      - name: Run deploy script
        run: |
          ssh -o StrictHostKeyChecking=yes ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash -s' -- < build/ci-deploy.sh ${{ secrets.WEBPATH }}
